name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: platformio/action-platformio-tool@v1
      - name: Build default env
        run: pio run -e esp32s
      - name: Build ESP8266 env
        run: pio run -e esp8266
